// <auto-generated />
using AlbumCopaDoMundo.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AlbumCopaDoMundo.Dados.Migrations
{
    [DbContext(typeof(AlbumCopaDoMundoDbContext))]
    [Migration("20180510045912_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("AlbumCopaDoMundo.Models.Figurinha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Colada");

                    b.Property<string>("Nacionalidade");

                    b.Property<string>("Nome");

                    b.Property<int>("Numero");

                    b.HasKey("Id");

                    b.ToTable("Figurinhas");
                });
#pragma warning restore 612, 618
        }
    }
}
